export const API_URI = {
  createSaleInv: 'api/SaleInvoice/CreateSaleInvoice',
  createSaleInvDetail: 'api/SaleInvDetail/CreateListSaleDetail',
  invoice: 'api/SaleInvoice/GetAllSaleInvoice',
  invoiceById: 'api/SaleInvoice/GetSaleInvoiceById',
  updateClient: 'api/client/UpdateClient',
  clientById: 'api/client/GetClientById',
  clientAll: 'api/Client/GetAllClientAsync',
  productGetAll: 'api/Product/GetAllProductAsync',
  paymentCreate: 'api/Payments/CreatePayments',
  paymentIvById: 'api/Payments/GetPaymentByInv',
  paymentById: 'api/Payments/GetPaymentById',
  updatePayment: 'api/Payments/UpdatePayment',
  deletePayment: 'api/Payments/DeletePayment',
  invoiceDF: 'api/SaleInvoice/GetDF',
  deleteSaleInvoice: 'api/SaleInvoice/DeleteSaleInv',
  updateSaleInv: 'api/SaleInvoice/UpdateSaleInvoice',
  deleteSaleInvoiceDetail: 'api/SaleInvDetail/DeletedSaleInvDetail',
  deleteClient: 'api/client/DeleteClient',
  createClient: 'api/client/SaveClient',
  taxGetAll: 'api/Tax/GetAllTax',
  createTax: 'api/Tax/CreateTax',
  deleteProduct: 'api/Product/DeleteProduct',
  getGen: 'api/GeneralLedger/GetAllGen',
  exportCSV: 'api/GeneralLedger/GetCSV',
  getAccountChart: 'api/AccountChart/GetAllAccount',
  createProduct: 'api/Product/CreateProduct',
  updateProduct: 'api/Product/UpdateProduct',
  productById: 'api/Product/GetProductById',
  categoryById: 'api/Category/GetCategoryById',
  categoryGetAll: 'api/Category/GetAllCategory',
  lastInvoice: 'api/SaleInvoice/GetLastIndexInvoiceAsync',
  uploadProfile: 'api/UploadProfile/Upload',
  getProfile: 'api/UploadProfile/GetAllProFile',
  getFile: 'api/UploadProfile/GetIMG',
  getClientDap: 'api/Client/GetAllClientDapper',
};
export const PAGING_CONFIG = {
  pageIndex: 1,
  pageSize: 20
};
